### ISSUE TITLE
Insert all rows in a single statement

### ISSUE THREAD

**Issue by dorofeev22** [dorofeev22/caregiving#33]
https://stackoverflow.com/questions/6687422/hibernate-batch-size-confusion?answertab=votes#tab-top
https://stackoverflow.com/questions/19175234/how-to-insert-all-rows-in-a-single-statement

POST /products

[
  {
    "number": "100",
    "name": "dfgdghfhfgjfg"
  },
  {
    "number": "101",
    "name": "dfgdghfhfgjfg"
  },
  {
    "number": "102",
    "name": "dfgdghfhfgjfg"
  },
  {
    "number": "103",
    "name": "dfgdghfhfgjfg"
  },
  {
    "number": "104",
    "name": "dfgdghfhfgjfg"
  }
]

**Comment by ForNeVeR** [comment]
Good materials on the matter:

- https://vladmihalcea.com/how-does-the-auto-flush-work-in-jpa-and-hibernate/
- https://www.hameister.org/SpringBootUsingIdsForBulkImports.html

**Comment by ForNeVeR** [comment]
For logging real PostgreSQL queries, see https://stackoverflow.com/a/722236
